### ISSUE TITLE
negative retention times

### ISSUE THREAD

**Issue by Seb-Leb** [compomics/DeepLC#34]
I am using DeepLC through the MS2PIP website along with the intensity predictor for a list of peptides. Many of the peptides are assigned a negative retention time and I am not sure how to interpret that result.
Thank you for your help!

**Comment by RobbinBouwmeester** [comment]
Dear Seb-Leb, there are several possibilities, but it is most likely that these values are iRT values (the default as returned by the MS2PIP webserver). Although negative retention times would nor make sense, iRT values can be negative. These values can be negative because they are indexed using specific points and peptides retention times are "normalized" towards these specific points.

**Comment by Seb-Leb** [comment]
That settles it, thank you!
